spring:
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/events/**
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/user/**
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
server:
  port: 8888

